# Paid ₪1 commitment users — sourced from Grow TransactionsReport 16-08-2026.
# Password for new accounts: env HANDOFF_PASSWORD_COMMITMENT (never commit plaintext).
CLIENT_HANDOFF_ACCOUNTS = (
    {
        "email": "sbl.school1@gmail.com",
        "password_env": "HANDOFF_PASSWORD_MICHAL",
        "full_name": "מיכל מזכירה",
        "role": "admin",
    },
    {
        "email": "shuliyazdi2000@gmail.com",
        "password_env": "HANDOFF_PASSWORD_SHULI",
        "full_name": "שולי בן לולו",
        "role": "admin",
    },
    {
        "email": "0527665134m@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "מיכל סיון",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "0777009146a@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "אריה אטינגר",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "avitalb717@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "באבל- אביטל מלכא",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "bn@lechatchila.org",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "בן ציון נוימן",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "chaya18g@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "מושקי נימץ",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "d0526114028@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "דבורה טכובר אומנות השיער",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "e6666668@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "אסתי לוי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "eh.designer20@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "אסתר חלימי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "hadasa.dadon@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "אביבית דדון",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "i@symfruit.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "נחמי רוזובסקי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "k4166887@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "פייגי איזנברג",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "leah22p@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "לאה פריאנטי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "m0504177214@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "מרים חנין",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "mh044616647@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": 'ד"ר מתוקה הורביץ',
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "mirielkin@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "מירי אלקין",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "mortaxes1@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "הגר מור",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "nech0329@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "נחמה גלינסקי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "noa.olanovski@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "נועה אולנובסקי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "rf0527600706@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "יהושע פרידמן",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "rivka.ara@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "רבקה ועזריה אהרונביוב",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "rk0556744410@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "רבקי קרליץ",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "rs.cpa95@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "רחלי סנדרוסי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "t0527196623@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "תמר ויינר",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "talyacohen55@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "טליה כהן",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "tehilakadosh10@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "תהילה קדוש",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "todaat.hashefa@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "אסתר חוגי",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "yaaras9@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "איתי פתיה",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "ydvir5@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "יעל דביר",
        "role": "user",
        "paid_commitment": True,
    },
    {
        "email": "yisraelmmi@gmail.com",
        "password_env": "HANDOFF_PASSWORD_COMMITMENT",
        "full_name": "ישראל מייקל",
        "role": "user",
        "paid_commitment": True,
    },
)
